version: '3.2'

services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ./:/app
    depends_on:
      - mysql
    links:
      - mysql

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ./:/app
    depends_on:
      - mysql
    links:
      - mysql

  

      